name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./accessibility-analyzer
          file: ./accessibility-analyzer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/accessibility-analyzer-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
