name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build_react_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./accessibility-analyzer

      - name: Build React app
        run: npm run build
        working-directory: ./accessibility-analyzer
